CREATE TABLE Members(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	Pin VARCHAR(11) NOT NULL,
	DateOfBirth TIMESTAMP NOT NULL,
	Gender VARCHAR(1) NOT NULL, --M/F
	CityOfResidence VARCHAR(30) NOT NULL
)

CREATE TABLE Students(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	Pin VARCHAR(11) NOT NULL,
	DateOfBirth TIMESTAMP NOT NULL,
	Gender VARCHAR(1) NOT NULL, --M/F
	CityOfResidence VARCHAR(30) NOT NULL
)

CREATE TABLE Internships(
	Id SERIAL PRIMARY KEY,
	StartDate TIMESTAMP NOT NULL,
	EndDate TIMESTAMP NOT NULL,
	Phase VARCHAR(30),
	Director INT REFERENCES Members(Id)
)

CREATE TABLE Areas(
	Id SERIAL PRIMARY KEY,
	Title VARCHAR(30) NOT NULL,
	Director INT REFERENCES Members(Id)
)

CREATE TABLE Homeworks (
	Id SERIAL PRIMARY KEY,
	Title VARCHAR(30) NOT NULL,
	AreaId INT REFERENCES Areas(Id)
)

-- STEP 1 -- PRIMARY TABLES